### ISSUE TITLE
How can the client send callback to the server when running the Emit function?

### ISSUE THREAD

**Issue by yucircle** [Baiguoshuai1/shadiaosocketio#1]
I have a program through socket.io 4.5 as a communication protocol, is the use of node.js development, I want to use golang as a client language, but encountered the do not know how to be able to send the callback to the server side of the problem, want to know the current have to do this function?

**Comment by Baiguoshuai1** [comment]
[5f4b5ea75932f099690dcea1a45c6f288473f956](https://github.com/Baiguoshuai1/shadiaosocketio/commit/5f4b5ea75932f099690dcea1a45c6f288473f956)

**Comment by shadiiiioa** [comment]
5f4b5ea75932f099690dcea1a45c6f288473f956
9e7421e240f735fa9c3c01c67dabe8e98c50e596
already supported! 
you can `go get -u github.com/Baiguoshuai1/shadiaosocketio@v0.0.6`
