### ISSUE TITLE
memory leak due to empty channel. 

### ISSUE THREAD

**Issue by m-almas** [Baiguoshuai1/shadiaosocketio#6]
This empties channel https://github.com/Baiguoshuai1/shadiaosocketio/blob/main/channel.go#L138 

And bloks this goroutime forever https://github.com/Baiguoshuai1/shadiaosocketio/blob/main/channel.go#L216. 
instead we should send protocol.CloseMsg so that for loop exits and go routine cleans itself

**Comment by shadiiiioa** [comment]
thanks, has been resolved https://github.com/Baiguoshuai1/shadiaosocketio/commit/50175dd658977bb916ce56f699b5f24b2652b4eb
